name: menfess_telegram_bot_dart
description: Menfesss Telegram bot dart.
version: 0.0.0
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/menfess_telegram_bot_dart
issue_tracker: https://github.com/azkadev/menfess_telegram_bot_dart 

environment:
  sdk: '>=2.18.0 <3.0.0'
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  alfred: ^0.1.7
  galaxeus_lib: ^0.0.27
  telegram_client: ^0.3.71
